# Section 0
##### Submission date: 
##### QPM-2025-2026: Assignment 1
##### Dongyang ZHAO, 
##### diversity


# Section 1: Questoin for Assignment 1

# Q 1.1

In [8]:
# downloading price data
import pandas as pd
import numpy as np
import yfinance as yf

tickers = ['META', 'AMZN', 'AAPL', 'NFLX', 'GOOG']

prices = yf.download(tickers=tickers,
                      start='2015-01-01',
                      end='2020-12-31', 
                      auto_adjust=False)['Adj Close']


prices = prices.reset_index('Date')  

prices


[*********************100%***********************]  5 of 5 completed


Ticker       Date        AAPL        AMZN       GOOG        META        NFLX
0      2015-01-02   24.237551   15.426000  25.990791   77.969337   49.848572
1      2015-01-05   23.554749   15.109500  25.448996   76.717056   47.311428
2      2015-01-06   23.556955   14.764500  24.859163   75.683426   46.501431
3      2015-01-07   23.887281   14.921000  24.816574   75.683426   46.742859
4      2015-01-08   24.805080   15.023000  24.894823   77.700996   47.779999
...           ...         ...         ...        ...         ...         ...
1505   2020-12-23  127.483307  159.263504  86.030266  266.467285  514.479980
1506   2020-12-24  128.466507  158.634506  86.351570  265.761627  513.969971
1507   2020-12-28  133.061188  164.197998  88.200920  275.302795  519.119995
1508   2020-12-29  131.289536  166.100006  87.338318  275.084198  530.869995
1509   2020-12-30  130.170029  164.292496  86.384842  270.204254  524.590027

[1510 rows x 6 columns]

In [9]:
# converting prices to returns

returns = prices.set_index('Date').pct_change()

returns


Ticker          AAPL      AMZN      GOOG      META      NFLX
Date                                                        
2015-01-02       NaN       NaN       NaN       NaN       NaN
2015-01-05 -0.028171 -0.020517 -0.020846 -0.016061 -0.050897
2015-01-06  0.000094 -0.022833 -0.023177 -0.013473 -0.017121
2015-01-07  0.014022  0.010600 -0.001713  0.000000  0.005192
2015-01-08  0.038422  0.006836  0.003153  0.026658  0.022188
...              ...       ...       ...       ...       ...
2020-12-23 -0.006976 -0.006627  0.005152  0.003819 -0.024368
2020-12-24  0.007712 -0.003949  0.003735 -0.002648 -0.000991
2020-12-28  0.035766  0.035071  0.021417  0.035901  0.010020
2020-12-29 -0.013315  0.011584 -0.009780 -0.000794  0.022634
2020-12-30 -0.008527 -0.010882 -0.010917 -0.017740 -0.011830

[1510 rows x 5 columns]

# Q 1.2

In [10]:
# calculate means, variances, covariances
mean = returns.mean()
variance = returns.var()
covariance = returns.cov()


print("Mean daily returns:\n", mean, "\n")

print("Variance of daily returns:\n", variance, "\n")

print("Covariance matrix:\n", covariance)

Mean daily returns:
 Ticker
AAPL    0.001289
AMZN    0.001757
GOOG    0.000939
META    0.001027
NFLX    0.001914
dtype: float64 

Variance of daily returns:
 Ticker
AAPL    0.000349
AMZN    0.000381
GOOG    0.000288
META    0.000403
NFLX    0.000715
dtype: float64 

Covariance matrix:
 Ticker      AAPL      AMZN      GOOG      META      NFLX
Ticker                                                  
AAPL    0.000349  0.000202  0.000192  0.000216  0.000206
AMZN    0.000202  0.000381  0.000216  0.000235  0.000275
GOOG    0.000192  0.000216  0.000288  0.000228  0.000216
META    0.000216  0.000235  0.000228  0.000403  0.000238
NFLX    0.000206  0.000275  0.000216  0.000238  0.000715


# Q 1.3

In [11]:
skewness = returns.skew()
excess_kurtosis = returns.kurtosis() - 3

print("Skewness:\n", skewness, "\n")

print("Excess Kurtosis:\n", excess_kurtosis)


Skewness:
 Ticker
AAPL   -0.082981
AMZN    0.759507
GOOG    0.517832
META   -0.329941
NFLX    0.682041
dtype: float64 

Excess Kurtosis:
 Ticker
AAPL    3.610325
AMZN    4.199629
GOOG    7.433338
META    9.041394
NFLX    4.350749
dtype: float64


# Q 2.1

In [93]:
import requests
# get the list
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
response = requests.get(url, headers=headers)
tables = pd.read_html(response.text)
sp500 = tables[1]

sp500_tickers = sp500['Symbol'].tolist()

start_date = '2000-01-01'
end_date = '2022-12-31'

# stock price
sp500_prices = yf.download(
    tickers=sp500_tickers,
    start=start_date,
    end=end_date,
    auto_adjust=False)['Adj Close']

# data cleaning
sp500_prices = sp500_prices.dropna(axis=1, how='all')

missing_counts = sp500_prices.isna().sum(axis=1) 

sp500_prices = sp500_prices[missing_counts <= 100]

sp500_prices = sp500_prices.loc[:, sp500_prices.isna().sum() <= 100]

sp500_prices = sp500_prices.reset_index('Date') 

sp500_prices


C:\Users\17475\AppData\Local\Temp\ipykernel_24480\4016645377.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)
[*********************100%***********************]  503 of 503 completed

8 Failed downloads:
['VLTO', 'SOLV', 'GEV', 'Q', 'KVUE', 'SOLS']: YFPricesMissingError('possibly delisted; no price data found  (1d 2000-01-01 -> 2022-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 946702800, endDate = 1672462800")')
['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (1d 2000-01-01 -> 2022-12-31)')
['BRK.B']: YFTzMissingError('possibly delisted; no timezone found')


Ticker       Date           A        AAPL         ABT       ACGL         ACN  \
0      2005-12-05   20.957869    2.153957   11.577961   5.503590   20.352814   
1      2005-12-06   20.921938    2.220837   11.480942   5.555360   20.409405   
2      2005-12-07   20.646490    2.217838   11.520353   5.546908   20.331589   
3      2005-12-08   20.706366    2.221736   11.608274   5.581774   19.977873   
4      2005-12-09   21.119528    2.229234   11.820487   5.686373   19.984941   
...           ...         ...         ...         ...        ...         ...   
4293   2022-12-23  146.000793  129.900284  102.049530  60.267948  254.155930   
4294   2022-12-27  146.313873  128.097504  102.417435  60.496162  253.410919   
4295   2022-12-28  144.885452  124.166786  101.719376  59.526245  251.319107   
4296   2022-12-29  147.820541  127.683754  104.058823  60.011208  256.343170   
4297   2022-12-30  146.630066  127.998970  103.568298  59.697407  254.872284   

Ticker        ADBE         ADI        ADM         ADP  ...        WSM  \
0        35.250000   24.474375  14.440796   23.036894  ...  14.130059   
1        36.990002   24.649380  14.588844   23.100784  ...  14.053776   
2        36.470001   24.468142  14.884938   23.103258  ...  13.882118   
3        36.130001   23.949383  15.199547   22.915747  ...  13.863039   
4        35.599998   24.024399  15.298240   23.024305  ...  13.913904   
...            ...         ...        ...         ...  ...        ...   
4293    338.450012  156.080734  86.630257  226.983612  ...  56.749355   
4294    335.089996  154.518402  87.811317  227.068405  ...  55.248260   
4295    328.329987  152.689331  85.714691  224.072647  ...  54.252243   
4296    337.579987  156.214111  85.256920  226.682159  ...  55.016960   
4297    336.529999  156.261734  85.009712  225.024109  ...  54.247517   

Ticker         WST         WTW         WY       WYNN        XEL        XOM  \
0        10.697725   64.130920  12.565408  29.932825   8.875087  30.149740   
1        10.466719   64.454140  12.589837  30.120956   8.879880  30.240931   
2        10.336513   64.335075  12.443269  30.094082   8.841520  29.901489   
3        10.294512   64.164963  12.420724  30.190817   8.870292  30.104143   
4        10.361713   63.314404  12.458304  30.475695   8.937421  29.638033   
...            ...         ...        ...        ...        ...        ...   
4293    233.265228  235.045609  28.382820  78.621727  64.013199  98.027603   
4294    234.852524  235.228363  28.364794  82.137894  64.590775  99.389610   
4295    229.406082  232.496948  27.607676  78.008095  64.125534  97.757027   
4296    237.084686  236.665939  28.229593  79.147697  64.579872  98.496651   
4297    233.483459  236.029007  27.941170  80.326241  63.707550  99.488831   

Ticker         YUM         ZBH        ZBRA  
0        12.086884   60.365738   43.930000  
1        12.017713   58.456108   43.799999  
2        11.894199   58.542515   43.400002  
3        11.980659   57.989483   43.110001  
4        11.889260   59.294289   43.349998  
...            ...         ...         ...  
4293    122.271065  123.750938  248.220001  
4294    123.219658  124.327248  251.000000  
4295    122.659988  123.067169  246.839996  
4296    123.305023  124.864510  257.529999  
4297    121.493263  124.542152  256.410004  

[4298 rows x 400 columns]

# Q 2.2

In [94]:

# Compute daily log-returns

prices = sp500_prices.set_index('Date').sort_index()

log_returns = np.log(prices / prices.shift(1)).dropna()

Ticker
JNJ     0.174065
PEP     0.185716
PG      0.185974
KO      0.189896
KMB     0.191949
          ...   
HIG     0.604394
LVS     0.619844
AIG     0.637620
UAL     0.664049
BLDR    0.709647
Length: 399, dtype: float64

# Q 2.3

In [ ]:
# Parameters
T = 252           
rf = 0.0           

# Annualized return
annualized_return = log_returns.mean() * T

# Annualized volatility
annualized_vol = log_returns.std() * np.sqrt(T)

# Annualized Sharpe ratio

excess_return = annualized_return - rf
annualized_sharpe = excess_return / annualized_vol


print("Annualized return (log-returns) :")
print(annualized_return.sort_values(ascending=False))

print("\n Annualized volatility :")
print(annualized_vol.sort_values())

print("\n Annualized Sharpe ratio :")
print(annualized_sharpe.sort_values(ascending=False))

# Q 2.4

In [ ]:
# No, it would not make sense to choose portfolio weights based only on 
# the Sharpe ratios of the individual stocks.
#
# The Sharpe ratio evaluates each asset in isolation and ignores the 
# covariances between assets, which are essential in portfolio construction. 
# As shown in the course, optimal mean-variance weights depend on the entire 
# covariance matrix V[R], not just individual risk–return profiles.
#
# In addition, Sharpe ratios rely on estimates of expected returns, which are 
# very imprecise and lead to poor out-of-sample performance.
#
# Selecting assets purely by Sharpe ratios also produces concentrated and 
# poorly diversified portfolios.
#
# Conclusion: the Sharpe ratio is useful for descriptive comparison, 
# but it should not be used alone to determine portfolio weights.


# Section 2: Questoin for Assignment 2

# Q 1.1

In [137]:
tickers = ['MMM','AOS','ABT','ADM','ADBE','ADP','AES','AFL','A','AKAM']

prices = sp500_prices[['Date','MMM','AOS','ABT','ADM','ADBE','ADP','AES','AFL','A','AKAM']]

prices_m = prices.set_index('Date').resample('M').last()
returns_m = prices_m.pct_change().dropna()

prices_m_60 = prices_m[:61]
returns_m_60 = prices_m_60.pct_change().dropna()


C:\Users\17475\AppData\Local\Temp\ipykernel_24480\3054981275.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  prices_m = prices.set_index('Date').resample('M').last()


# Q 1.2

In [139]:
# MV
rf = .0
mu = returns_m_60.mean()
excess_mu = mu - rf
sigma = returns_m_60.cov()

w_mv = np.linalg.solve(sigma, excess_mu)
w_mv /= w_mv.sum()

w_mv

array([ 0.25250959,  0.12607499,  0.52121069,  0.06073933, -0.22447168,
        0.05088938, -0.22508571,  0.12786471,  0.09568732,  0.21458139])

In [140]:
# GMV

n = len(tickers)
e = np.ones(n)

u = np.linalg.solve(sigma, e)
w_gmv = u / u.sum()

w_gmv


array([ 0.40511404,  0.06260707,  0.48226549, -0.00088868, -0.02494779,
        0.22078721, -0.01627979, -0.08920613, -0.14459085,  0.10513941])

In [148]:
returns_m

Ticker           MMM       AOS       ABT       ADM      ADBE       ADP  \
Date                                                                     
2006-01-31 -0.061290  0.232262  0.101557  0.277372  0.074946 -0.042702   
2006-02-28  0.017943  0.074495  0.023871  0.010254 -0.029700  0.051206   
2006-03-31  0.028536  0.140389 -0.038705  0.060845 -0.093385 -0.007030   
2006-04-30  0.128683 -0.098891  0.013445  0.079941  0.121602 -0.035026   
2006-05-31 -0.015499 -0.073176 -0.000936  0.146516 -0.269643  0.031533   
...              ...       ...       ...       ...       ...       ...   
2022-08-31 -0.122967 -0.107792 -0.056873  0.066813 -0.089437  0.013645   
2022-09-30 -0.111379 -0.139415 -0.057379 -0.084651 -0.263068 -0.070548   
2022-10-31  0.138371  0.134180  0.027355  0.205469  0.157340  0.068571   
2022-11-30  0.013157  0.108799  0.087326  0.009646  0.082983  0.092842   
2022-12-31 -0.048027 -0.057623  0.020543 -0.047692 -0.024353 -0.091325   

Ticker           AES       AFL         A      AKAM  
Date                                                
2006-01-31  0.076437  0.011418  0.018624  0.097842  
2006-02-28  0.015258 -0.012209  0.061634  0.211152  
2006-03-31 -0.013873 -0.024216  0.043056  0.241132  
2006-04-30 -0.005275  0.053401  0.023169  0.024323  
2006-05-31  0.084266 -0.012923 -0.091879 -0.071238  
...              ...       ...       ...       ...  
2022-08-31  0.145364  0.043709 -0.043624 -0.061734  
2022-09-30 -0.111984 -0.054190 -0.052242 -0.110323  
2022-10-31  0.164476  0.158541  0.140184  0.099726  
2022-11-30  0.105505  0.111215  0.120203  0.073927  
2022-12-31 -0.005533  0.000139 -0.032951 -0.111322  

[204 rows x 10 columns]

# Q 1.3

In [ ]:
T = 60
rf = 0.0
n_months = len(returns_m)
weights_mvp = []
weights_gmv = []

for i in range(T, n_months): 
    rolling_returns = returns_m.iloc[i-T:i]  

    mu = rolling_returns.mean()  
    sigma = rolling_returns.cov()  

    excess_mu = mu - rf
    w_mvp = np.linalg.solve(sigma, excess_mu)
    w_mvp /= w_mvp.sum()
    weights_mvp.append(w_mvp)

    e = np.ones(len(mu))
    w_gmv = np.linalg.solve(sigma, e)
    w_gmv /= w_gmv.sum()
    weights_gmv.append(w_gmv)

weights_mvp = pd.DataFrame(weights_mvp, columns=returns_m.columns, index=returns_m.index[T:])
weights_gmv = pd.DataFrame(weights_gmv, columns=returns_m.columns, index=returns_m.index[T:])

# Q 1.4

In [175]:
R_mvp = (weights_mvp.values * returns_m.iloc[T:].values).sum(axis=1)
R_gmv = (weights_gmv.values * returns_m.iloc[T:].values).sum(axis=1)
R_mvp

array([-8.78287759e-03, -5.35135316e-03,  1.39961265e-02,  4.50611590e-02,
       -3.16500429e-02,  5.44662681e-04, -6.25113066e-02, -1.34771382e-02,
       -8.77814405e-02,  1.01069567e-01,  1.46987098e-03,  2.47306090e-02,
       -5.31579413e-03, -5.02739131e-03,  5.03252583e-02,  3.63675532e-02,
       -2.85886189e-02, -1.33955879e-03,  7.61455499e-02,  6.40206447e-02,
        7.78260261e-02,  2.51029320e-02, -6.62203731e-03, -9.10156084e-03,
        1.08326168e-01, -5.56561816e-02,  2.44660992e-02,  7.12774965e-02,
        3.89946031e-02, -8.93826372e-02,  1.05136226e-01, -5.29076863e-02,
        3.06328474e-02,  8.56549041e-02,  4.62101424e-02, -7.16788844e-05,
       -6.32739673e-02,  8.71545758e-02, -5.97484384e-02,  2.27201950e-03,
        4.26756800e-02, -2.92469424e-03,  2.26612088e-02,  2.72203699e-02,
        1.79515219e-02,  1.09066134e-01,  8.32862224e-02, -2.15215661e-02,
        2.99631235e-02,  8.09737957e-02, -3.26075514e-02,  1.10201264e-02,
        1.01430153e-01, -

# Q 1.5

In [223]:
SR_mvp = (R_mvp - rf) / R_mvp.std()
SR_gmv = (R_gmv - rf) / R_gmv.std()

SR_mvp.mean() - SR_gmv.mean()

np.float64(-0.016523128788518526)

# Q 2.1

In [ ]:
# solve function
import cvxpy as cp

def solve_mvp(mu, sigma):
    mu = np.array(mu).flatten()          # ensure 1D array
    sigma = np.array(sigma)              # ensure matrix

    n = len(mu)
    w = cp.Variable(n)

    objective = cp.Maximize(mu @ w)
    constraints = [
        cp.sum(w) == 1,
        w >= 0
    ]

    prob = cp.Problem(objective, constraints)
    prob.solve()

    return w.value


def solve_gmv(sigma):
    sigma = np.array(sigma)
    n = sigma.shape[0]

    w = cp.Variable(n)

    objective = cp.Minimize(cp.quad_form(w, sigma))
    constraints = [
        cp.sum(w) == 1,
        w >= 0
    ]

    prob = cp.Problem(objective, constraints)
    prob.solve()

    return w.value

rf = .0
mu = returns_m_60.mean()
excess_mu = mu - rf
sigma = returns_m_60.cov()

w_mvp = solve_mvp(excess_mu, sigma)
w_gmv = solve_gmv(sigma)

w_gmv


np.float64(0.9999999999999999)

In [211]:
# minimize function

# MV
rf = .0
mu = returns_m_60.mean()
excess_mu = mu - rf
sigma = returns_m_60.cov()
n = len(mu)


from scipy.optimize import minimize

w_mv_c = np.ones(n) / n
constraints = {'type': 'eq', 'fun': lambda w: np.sum(w) - 1}
bounds = [(0, 1) for _ in range(n)]

def sharpe_ratio(w, mu, cov_matrix, rf):
    port_return = w.T @ mu
    port_vol = np.sqrt(w.T @ cov_matrix @ w)
    return -(port_return - rf) / port_vol

result = minimize(sharpe_ratio, 
                  w_mv_c, 
                  args=(mu, sigma, rf),
                  method='SLSQP', 
                  bounds=bounds, 
                  constraints=constraints)

w_mv = result.x
print(w_mv)

[1.68650221e-01 1.63600151e-01 4.11263354e-01 6.06648016e-02
 0.00000000e+00 3.69894133e-03 0.00000000e+00 0.00000000e+00
 8.50150029e-17 1.92122530e-01]


In [212]:
# minimize function

# GMV
mu = returns_m_60.mean()
sigma = returns_m_60.cov()
n = len(mu)
ones = np.ones(len(sigma))

w_gmv_c = np.ones(n) / n
constraints = {'type': 'eq', 'fun': lambda w: np.sum(w) - 1}
bounds = [(0, 1) for _ in range(n)]

def portfolio_variance(w, cov_matrix): 
    return w.T @ cov_matrix @ w

result = minimize(portfolio_variance, 
                  w_gmv_c, 
                  args=(sigma,),
                  method='SLSQP', 
                  bounds=bounds, 
                  constraints=constraints)

w_gmv = result.x
print(w_gmv)

[2.06964027e-01 3.51426160e-02 4.39165072e-01 3.26278416e-02
 9.97465999e-18 2.04678688e-01 7.80625564e-18 0.00000000e+00
 1.04083409e-17 8.14217550e-02]


# Q 2.2

In [213]:
T = 60
rf = 0.0
n_months = len(returns_m)
weights_mvp_c = []
weights_gmv_c = []

for i in range(T, n_months): 
    rolling_returns = returns_m.iloc[i-T:i]  

    mu = rolling_returns.mean()  
    sigma = rolling_returns.cov()  

    excess_mu = mu - rf
    w_mv_c = solve_mvp(excess_mu, sigma)

    w_gmv_c = solve_gmv(sigma)

weights_mvp_c = pd.DataFrame(weights_mvp, columns=returns_m.columns, index=returns_m.index[T:])
weights_gmv_c = pd.DataFrame(weights_gmv, columns=returns_m.columns, index=returns_m.index[T:])

weights_mvp_c

Ticker           MMM       AOS       ABT       ADM      ADBE       ADP  \
Date                                                                     
2011-01-31  0.252510  0.126075  0.521211  0.060739 -0.224472  0.050889   
2011-02-28  0.294655  0.128437  0.444974  0.042554 -0.226151  0.122335   
2011-03-31  0.302856  0.089146  0.464743  0.084171 -0.187197  0.109100   
2011-04-30  0.298707  0.097109  0.469139  0.054436 -0.172881  0.157841   
2011-05-31  0.117666  0.159188  0.480143  0.040797 -0.229974  0.269721   
...              ...       ...       ...       ...       ...       ...   
2022-08-31 -1.303837 -0.267136  0.772430  0.486912  0.329615  0.516553   
2022-09-30 -1.283036 -0.286633  0.746664  0.518452  0.290885  0.643353   
2022-10-31 -1.527631 -0.401819  0.815945  0.524973  0.248258  0.748882   
2022-11-30 -1.577417 -0.275836  0.782720  0.613695  0.177989  0.645762   
2022-12-31 -1.720586 -0.353710  0.815820  0.743814  0.210036  0.768576   

Ticker           AES       AFL         A      AKAM  
Date                                                
2011-01-31 -0.225086  0.127865  0.095687  0.214581  
2011-02-28 -0.222490  0.111983  0.084001  0.219701  
2011-03-31 -0.235645  0.112231  0.077562  0.183034  
2011-04-30 -0.199603  0.074481  0.053328  0.167444  
2011-05-31 -0.210456  0.106365  0.114413  0.152137  
...              ...       ...       ...       ...  
2022-08-31 -0.154240 -0.003843  0.584388  0.039158  
2022-09-30 -0.157876 -0.031231  0.515955  0.043467  
2022-10-31 -0.204839  0.012252  0.762065  0.021913  
2022-11-30 -0.128527  0.020244  0.722485  0.018885  
2022-12-31 -0.176416 -0.051858  0.820222 -0.055899  

[144 rows x 10 columns]

In [220]:
# minimizing function
# mv
rf = 0.0
window = 60
rolling_weights_mv = pd.DataFrame(index=returns_m_60.index[window-1:], 
                               columns=returns_m_60.columns)

n = returns_m_60.shape[1]
w0 = np.ones(n) / n
bounds = [(0, 1) for _ in range(n)]
constraints = {'type': 'eq', 'fun': lambda w: np.sum(w)-1}

for i in range(window-1, len(returns_m_60)):

    roll_data = returns_m_60.iloc[i-window+1:i+1]
    
    mu_roll = roll_data.mean().values
    sigma_roll = roll_data.cov().values

    result = minimize(sharpe_ratio, w0, args=(mu_roll, sigma_roll, rf),
                      method='SLSQP', bounds=bounds, constraints=constraints)
    
    rolling_weights_mv.iloc[i-window+1] = result.x

rolling_weights_mv


Ticker          MMM     AOS       ABT       ADM ADBE       ADP  AES  AFL    A  \
Date                                                                            
2010-12-31  0.16865  0.1636  0.411263  0.060665  0.0  0.003699  0.0  0.0  0.0   

Ticker          AKAM  
Date                  
2010-12-31  0.192123

In [221]:
# minimizing function
# gmv
window = 60
n = returns_m_60.shape[1]

rolling_weights_gmv = pd.DataFrame(index=returns_m_60.index[window-1:], 
                                   columns=returns_m_60.columns)

w0 = np.ones(n) / n 
bounds = [(0, 1) for _ in range(n)]
constraints = {'type': 'eq', 'fun': lambda w: np.sum(w) - 1}

for i in range(window-1, len(returns_m_60)):

    roll_data = returns_m_60.iloc[i-window+1:i+1]
    
    sigma_roll = roll_data.cov().values
    
    result = minimize(portfolio_variance, w0, args=(sigma_roll,), 
                      method='SLSQP', bounds=bounds, constraints=constraints)

    rolling_weights_gmv.iloc[i-window+1] = result.x

rolling_weights_gmv

Ticker           MMM       AOS       ABT       ADM ADBE       ADP  AES  AFL  \
Date                                                                          
2010-12-31  0.206964  0.035143  0.439165  0.032628  0.0  0.204679  0.0  0.0   

Ticker        A      AKAM  
Date                       
2010-12-31  0.0  0.081422

# Q 2.3

In [216]:
R_mvp_c = (weights_mvp_c.values * returns_m.iloc[T:].values).sum(axis=1)
R_gmv_c = (weights_gmv_c.values * returns_m.iloc[T:].values).sum(axis=1)
R_mvp

array([-8.78287759e-03, -5.35135316e-03,  1.39961265e-02,  4.50611590e-02,
       -3.16500429e-02,  5.44662681e-04, -6.25113066e-02, -1.34771382e-02,
       -8.77814405e-02,  1.01069567e-01,  1.46987098e-03,  2.47306090e-02,
       -5.31579413e-03, -5.02739131e-03,  5.03252583e-02,  3.63675532e-02,
       -2.85886189e-02, -1.33955879e-03,  7.61455499e-02,  6.40206447e-02,
        7.78260261e-02,  2.51029320e-02, -6.62203731e-03, -9.10156084e-03,
        1.08326168e-01, -5.56561816e-02,  2.44660992e-02,  7.12774965e-02,
        3.89946031e-02, -8.93826372e-02,  1.05136226e-01, -5.29076863e-02,
        3.06328474e-02,  8.56549041e-02,  4.62101424e-02, -7.16788844e-05,
       -6.32739673e-02,  8.71545758e-02, -5.97484384e-02,  2.27201950e-03,
        4.26756800e-02, -2.92469424e-03,  2.26612088e-02,  2.72203699e-02,
        1.79515219e-02,  1.09066134e-01,  8.32862224e-02, -2.15215661e-02,
        2.99631235e-02,  8.09737957e-02, -3.26075514e-02,  1.10201264e-02,
        1.01430153e-01, -

In [ ]:
R_mvp_c = (rolling_weights_mv.values * returns_m.iloc[T:].values).sum(axis=1)
R_gmv_c = (rolling_weights_gmv.values * returns_m.iloc[T:].values).sum(axis=1)
R_mvp_c

array([0.014616093568030657, -0.007166482748687357, 0.02702103217705633,
       0.018939938086320655, -0.021557834352255122, -0.011324321639580588,
       -0.06672006933836012, -0.027693564186461905, -0.08974579227777797,
       0.1486822562065398, 0.0367782100493413, 0.03726096692080288,
       0.008589579988830174, 0.060149692140722216, 0.0410554394851948,
       -0.0038357214745728327, -0.03196748996329969, 0.049452331606047006,
       0.034323765538081086, 0.031141223444566636, 0.03196414311911649,
       -0.016690209241276604, 0.0034489816456237127, 0.031113774694475585,
       0.06629031043403028, 0.0010095425422765696, 0.022317905941651454,
       0.0696316425839134, 0.020637458492698435, -0.045347077701771495,
       0.08386751867850022, -0.0455909355512749, 0.04597910569298361,
       0.05747081118281642, 0.03690230326981828, 0.0247622781632771,
       -0.05423883495414703, 0.11026997210569522, -0.02908943639813814,
       -0.0041172583511774954, 0.03459935576804265, 0.0332697

# Q 2.4

In [224]:
SR_mvp_c = (R_mvp_c - rf) / R_mvp_c.std()
SR_gmv_c = (R_gmv_c -rf) / R_gmv_c.std()

SR_mvp_c

array([0.30631498699905807, -0.15019068260445725, 0.566289965337938,
       0.39693142779024854, -0.4517956674677074, -0.23732808083471105,
       -1.3982776640577927, -0.5803844723796904, -1.880836426424967,
       3.1159901354567827, 0.7707748230179486, 0.7808921408988976,
       0.1800150683463636, 1.2605797903745348, 0.8604143339404273,
       -0.08038666201382932, -0.6699547472738323, 1.0363911699438038,
       0.719336103427302, 0.6526383681219455, 0.6698846061976484,
       -0.34978301164789577, 0.07228160951637673, 0.6520631143109223,
       1.389271044568132, 0.02115736392033166, 0.4677247745126659,
       1.4592966029902301, 0.43250700335632, -0.9503558151164044,
       1.7576432289567956, -0.9554664360666998, 0.9636014641682574,
       1.2044374715002377, 0.7733754914551171, 0.5189524053295507,
       -1.136703726374828, 2.310969406067754, -0.6096382929290591,
       -0.08628693654994345, 0.7251117518462741, 0.697246011361993,
       -0.00897549539893936, 0.49785318735383377